---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myweb
  name: myweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - image: siva1490/github-jenkins-k8s:${BUILD_NUMBER}
        imagePullPolicy: Always
        name: myweb
        ports:
          - containerPort: 8080
